all: bracket arrays caps ex1 ex2 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 2D ex13 ex14 ex15 ex16 ex17 compute

compute:
	gcc -g compute.c -o compute

bracket:
	gcc -g bracket.c -o bracket

arrays:
	gcc -g arrays.c -o arrays

caps:
	gcc -g caps.c -o caps

2D:
	gcc -g 2D.c -o 2D

ex1:
	gcc -g ex1.c -o ex1

ex2:
	gcc -g ex2.c -o ex2

ex4:
	gcc -g ex4.c -o ex4

ex5:
	gcc -g ex5.c -o ex5

ex6:
	gcc -g ex6.c -o ex6

ex7:
	gcc -g ex7.c -o ex7

ex8:
	gcc -g ex8.c -o ex8

ex9:
	gcc -g ex9.c -o ex9

ex10:
	gcc -g ex10.c -o ex10

ex11:
	gcc -g ex11.c -o ex11

ex12:
	gcc -g ex12.c -o ex12

ex13:
	gcc -g ex13.c -o ex13

ex14:
	gcc -g ex14.c -o ex14

ex15:
	gcc -g ex15.c -o ex15

ex16:
	gcc -g ex16.c -o ex16

ex17:
	gcc -g ex17.c -o ex17
clean:
	rm -f bracket caps ex2 ex1 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 2D ex13 ex14 ex15 arrays ex16 ex17 compute
